### ISSUE TITLE
Adding hover effect and pop up on navbar and homepage.

### ISSUE THREAD

**Issue by shobhit15082003** [intentjs/core#27]
**Is your feature request related to a problem? Please describe.**
The hover effect on the navbar and homepage looks pleasing and also the hover change colors are present on footer but are missing in navbar.

**Describe the solution you'd like**
Adding simple CSS/Tailwind

**Describe alternatives you've considered**
N/A

**Additional context**
![Screenshot 2024-10-08 170212](https://github.com/user-attachments/assets/0c2249fc-918d-4a6f-b5fc-e0a95ef048ae)

**Comment by vinayak25** [comment]
Thanks for raising this bug @shobhit15082003! I wouldn't ever notice this thing.

**Comment by shobhit15082003** [comment]
@vinayak25 if you could assign it to me I can fix it easily.

**Comment by vinayak25** [comment]
My bad, I fixed it already. 

Also, since the homepage is part of a private repository right now, couldn't assign :)

Thanks for raising this issue!
